require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Auto-select archs (removes ARCHS override, lets Xcode decide)
      config.build_settings.delete('ARCHS')
      # Suppress Capacitor header include-style warnings
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      # Disable code signing for Pods targets
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end

  # Remove ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES from Pods-App aggregate target
  pods_app = installer.pods_project.targets.find { |t| t.name == 'Pods-App' }
  if pods_app
    pods_app.build_configurations.each do |config|
      config.build_settings.delete('ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES')
    end
  end

  # Project-level: dead code stripping, symbol stripping, parallelization
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
    config.build_settings.delete('STRIP_INSTALLED_PRODUCT')
    config.build_settings.delete('STRIP_STYLE')
    config.build_settings.delete('STRIP_SWIFT_SYMBOLS')
  end

  installer.pods_project.build_configuration_list.set_setting('PARALLELIZE_TARGETS', 'YES')
end
