import type WebSocket from 'ws'
import type { MultiplayerRoom } from './Room.js'
import type { RoomOrchestration, RoutingResolver, OrchestrationContext } from './orchestration/RoomOrchestration.js'

// Owns the live set of multiplayer rooms keyed by routing key. Decides
// whether to reuse an existing open room or spin up a new one, and keeps a
// stable per-key index so observer URLs (`/observe/{key}/{i}/{j}`) survive
// room churn.
//
// The router is orchestration-agnostic: it delegates room construction to an
// orchestration resolved from the routing key. The single-open-room policy
// of the original scenario registry is now a property of
// `DefaultScenarioOrchestration`, not of the router — the router supports
// an arbitrary number of concurrent open rooms per key.
export class RoomRouter {
  private readonly openRooms: Map<string, MultiplayerRoom[]> = new Map()
  private readonly allRooms: Map<string, (MultiplayerRoom | null)[]> = new Map()
  private readonly orchestrationByKey: Map<string, RoomOrchestration> = new Map()

  constructor(private readonly resolver: RoutingResolver) {}

  prewarm(routingKey: string): MultiplayerRoom | null {
    return this.ensureRoomForKey(routingKey)
  }

  // Route a newly connected player to an open room for the given key,
  // creating one if none exist. Returns null if the key is unknown — callers
  // should close the connection with 4004 in that case. The caller receives
  // both the room and the playerId generated by `room.connectPlayer`.
  routePlayer(routingKey: string, ws: WebSocket): { room: MultiplayerRoom; playerId: string } | null {
    const orch = this.resolveOrchestration(routingKey)
    if (!orch) return null
    const room = this.pickOpenRoomForKey(routingKey) ?? this.ensureRoomForKey(routingKey)
    if (!room) return null
    const playerId = room.connectPlayer(ws)
    return { room, playerId }
  }

  getRoomByIndex(routingKey: string, i: number): MultiplayerRoom | null {
    return this.allRooms.get(routingKey)?.[i] ?? null
  }

  hasRoomAndPlayer(routingKey: string, i: number, j: number): boolean {
    const room = this.getRoomByIndex(routingKey, i)
    return room !== null && room.getPlayerIdByIndex(j) !== null
  }

  private resolveOrchestration(routingKey: string): RoomOrchestration | null {
    const cached = this.orchestrationByKey.get(routingKey)
    if (cached) return cached
    const orch = this.resolver(routingKey)
    if (!orch) return null
    this.orchestrationByKey.set(routingKey, orch)
    return orch
  }

  // Picks a random open room for the key, or null if there isn't one. Also
  // lazily prunes rooms whose orchestration now reports them closed — this
  // normally happens via the onClose callback, but polling isOpen here
  // guards against an orchestration that forgets to fire the callback.
  private pickOpenRoomForKey(routingKey: string): MultiplayerRoom | null {
    const orch = this.resolveOrchestration(routingKey)
    if (!orch) return null
    const open = this.openRooms.get(routingKey)
    if (!open || open.length === 0) return null
    for (let i = open.length - 1; i >= 0; i--) {
      if (!orch.isOpen(open[i])) open.splice(i, 1)
    }
    if (open.length === 0) {
      this.openRooms.delete(routingKey)
      return null
    }
    return open[Math.floor(Math.random() * open.length)]
  }

  private ensureRoomForKey(routingKey: string): MultiplayerRoom | null {
    const orch = this.resolveOrchestration(routingKey)
    if (!orch) return null

    const slots = this.allRooms.get(routingKey) ?? []
    if (!this.allRooms.has(routingKey)) this.allRooms.set(routingKey, slots)
    const nullSlot = slots.findIndex(r => r === null)
    const instanceIndex = nullSlot !== -1 ? nullSlot : slots.length

    let room!: MultiplayerRoom
    const ctx: OrchestrationContext = {
      routingKey,
      instanceIndex,
      onClose: () => this.removeFromOpen(routingKey, room),
      onDestroy: () => this.freeSlot(routingKey, instanceIndex),
    }
    room = orch.createRoom(ctx)

    if (nullSlot !== -1) slots[nullSlot] = room
    else slots.push(room)

    const open = this.openRooms.get(routingKey) ?? []
    if (!this.openRooms.has(routingKey)) this.openRooms.set(routingKey, open)
    open.push(room)

    return room
  }

  private removeFromOpen(routingKey: string, room: MultiplayerRoom): void {
    const open = this.openRooms.get(routingKey)
    if (!open) return
    const idx = open.indexOf(room)
    if (idx >= 0) open.splice(idx, 1)
    if (open.length === 0) this.openRooms.delete(routingKey)
  }

  private freeSlot(routingKey: string, instanceIndex: number): void {
    const slots = this.allRooms.get(routingKey)
    if (slots) slots[instanceIndex] = null
  }
}
