import type WebSocket from 'ws'
import type { MultiplayerRoom } from './Room.js'
import type { RoomOrchestration, RoutingResolver, OrchestrationContext } from './orchestration/RoomOrchestration.js'
import type { PlayerRecordingManager } from './PlayerRecordingManager.js'

// Owns the live set of multiplayer rooms keyed by routing key. Decides
// whether to reuse an existing open room or spin up a new one, and keeps a
// stable per-key index so observer URLs (`/observe/{key}/{i}/{j}`) survive
// room churn.
//
// The router is orchestration-agnostic: it delegates room construction to an
// orchestration resolved from the routing key. The single-open-room policy
// of the original scenario registry is now a property of
// `DefaultScenarioOrchestration`, not of the router — the router supports
// an arbitrary number of concurrent open rooms per key.
export class RoomRouter {
  private readonly openRooms: Map<string, MultiplayerRoom[]> = new Map()
  private readonly allRooms: Map<string, (MultiplayerRoom | null)[]> = new Map()
  // Promise-keyed so concurrent cold-start requests for the same key share a
  // single backend load rather than racing to construct duplicate orchestrations.
  private readonly orchestrationByKey: Map<string, Promise<RoomOrchestration | null>> = new Map()

  constructor(
    private readonly resolver: RoutingResolver,
    private readonly recordingManager?: PlayerRecordingManager,
  ) {}

  // Route a newly connected player to an open room for the given key,
  // creating one if none exist. Returns null if the key is unknown — callers
  // should close the connection with 4004 in that case. The caller receives
  // both the room and the playerId generated by `room.connectPlayer`.
  //
  // The only await is the orchestration lookup; after it, the pick/ensure/
  // connectPlayer sequence runs synchronously so two continuations resolving
  // off the same shared promise end up in the same room (first creates it,
  // second picks it) with no explicit per-key lock.
  async routePlayer(routingKey: string, ws: WebSocket, browserUuid: string | null = null): Promise<{ room: MultiplayerRoom; playerId: string } | null> {
    const orch = await this.resolveOrchestration(routingKey)
    if (!orch) return null
    const room = this.pickOpenRoomForKey(routingKey, orch) ?? this.ensureRoomForKey(routingKey, orch)
    const playerId = room.connectPlayer(ws, browserUuid, routingKey)
    return { room, playerId }
  }

  getRoomByIndex(routingKey: string, i: number): MultiplayerRoom | null {
    return this.allRooms.get(routingKey)?.[i] ?? null
  }

  hasRoomAndPlayer(routingKey: string, i: number, j: number): boolean {
    const room = this.getRoomByIndex(routingKey, i)
    return room !== null && room.getPlayerIdByIndex(j) !== null
  }

  // Returns true if `routingKey` resolves to a valid orchestration (i.e. a
  // WebSocket connection with that path would be accepted). Shares the
  // router's orchestration cache so a successful check is free for the
  // subsequent routePlayer call.
  async canRouteKey(routingKey: string): Promise<boolean> {
    return (await this.resolveOrchestration(routingKey)) !== null
  }

  // Find (or create) a hub-capable room for `routingKey` that currently has
  // an open hub slot. Used by the hub transfer flow: the server picks a
  // target MR for a waiting solo-hallway player. If no open room exists,
  // creates a fresh one and returns it.
  async findOrCreateHubSlot(routingKey: string): Promise<MultiplayerRoom | null> {
    const orch = await this.resolveOrchestration(routingKey)
    if (!orch) return null
    const open = this.openRooms.get(routingKey)
    if (open) {
      for (const room of open) {
        if (orch.isOpen(room) && room.isHubSlotOpen()) return room
      }
    }
    return this.ensureRoomForKey(routingKey, orch)
  }

  private async resolveOrchestration(routingKey: string): Promise<RoomOrchestration | null> {
    const cached = this.orchestrationByKey.get(routingKey)
    if (cached) return cached
    const p = this.resolver(routingKey)
    this.orchestrationByKey.set(routingKey, p)
    p.then(
      v => { if (v === null) this.orchestrationByKey.delete(routingKey) },
      () => { this.orchestrationByKey.delete(routingKey) },
    )
    return p
  }

  // Picks a random open room for the key, or null if there isn't one. Also
  // lazily prunes rooms whose orchestration now reports them closed — this
  // normally happens via the onClose callback, but polling isOpen here
  // guards against an orchestration that forgets to fire the callback.
  private pickOpenRoomForKey(routingKey: string, orch: RoomOrchestration): MultiplayerRoom | null {
    const open = this.openRooms.get(routingKey)
    if (!open || open.length === 0) return null
    for (let i = open.length - 1; i >= 0; i--) {
      if (!orch.isOpen(open[i])) open.splice(i, 1)
    }
    if (open.length === 0) {
      this.openRooms.delete(routingKey)
      return null
    }
    return open[Math.floor(Math.random() * open.length)]
  }

  private ensureRoomForKey(routingKey: string, orch: RoomOrchestration): MultiplayerRoom {
    const slots = this.allRooms.get(routingKey) ?? []
    if (!this.allRooms.has(routingKey)) this.allRooms.set(routingKey, slots)
    const nullSlot = slots.findIndex(r => r === null)
    const instanceIndex = nullSlot !== -1 ? nullSlot : slots.length

    let room!: MultiplayerRoom
    const ctx: OrchestrationContext = {
      routingKey,
      instanceIndex,
      onClose: () => this.removeFromOpen(routingKey, room),
      onDestroy: () => this.freeSlot(routingKey, instanceIndex),
      recordingManager: this.recordingManager,
    }
    room = orch.createRoom(ctx)

    if (nullSlot !== -1) slots[nullSlot] = room
    else slots.push(room)

    const open = this.openRooms.get(routingKey) ?? []
    if (!this.openRooms.has(routingKey)) this.openRooms.set(routingKey, open)
    open.push(room)

    return room
  }

  private removeFromOpen(routingKey: string, room: MultiplayerRoom): void {
    const open = this.openRooms.get(routingKey)
    if (!open) return
    const idx = open.indexOf(room)
    if (idx >= 0) open.splice(idx, 1)
    if (open.length === 0) this.openRooms.delete(routingKey)
  }

  private freeSlot(routingKey: string, instanceIndex: number): void {
    const slots = this.allRooms.get(routingKey)
    if (slots) slots[instanceIndex] = null
  }
}
